apiVersion: batch/v1
kind: CronJob
metadata:
  name: ti-collector-cron
  namespace: ti-collector
spec:
  schedule: "@daily"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
            runAsNonRoot: true
          volumes:
            - name: ti-mount
              persistentVolumeClaim:
                claimName: ti-collector-pvc
          containers:
            - name: ti-collector-cron
              image: gclef/ticollector:1.5
              imagePullPolicy: IfNotPresent
              securityContext:
                allowPrivilegeEscalation: false
                capabilities:
                  drop:
                    - ALL
              volumeMounts:
                - name: ti-mount
                  mountPath: /RAID