apiVersion: v1
kind: PersistentVolume
metadata:
  name: ti-collector-pv
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: minio-nfs
  mountOptions:
    - nfsvers=4.1
  nfs:
    server: 192.168.1.197
    path: /volume1/minio/ti-collector
