kind: CronJob
apiVersion: batch/v1
metadata:
  name: ti-collector-cron
spec:
  schedule: "@daily"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          volumes:
            - name: ti-mount
              persistentVolumeClaim:
                claimName: ti-collector-pvc
          containers:
            - name: ti-collector-cron
              image: gclef/ticollector:1.4
              imagePullPolicy: "IfNotPresent"
              volumeMounts:
                - name: ti-mount
                  mountPath: /RAID
          imagePullSecrets:
            - name: registrycreds