kind: CronJob
apiVersion: batch/v1beta1
metadata:
  name: ti-collector-cron
spec:
  schedule: "@daily"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          volumes:
            - name: ti-mount
              nfs:
                server: <IP>
                path: <share>
          containers:
            - name: ti-collector
              image: gclef/ticollector:1.0
              imagePullPolicy: "IfNotPresent"
              volumeMounts:
                - name: malware-mount
                  mountPath: /RAID
          imagePullSecrets:
            - name: <>