apiVersion: v1
kind: PersistentVolume
metadata:
  name: ti-collector-pv
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ti-collector
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
    - vers=3.0
  csi:
    driver: smb.csi.k8s.io
    readOnly: false
    volumeHandle: ti-collector-pv
    volumeAttributes:
      source: "//192.168.1.197/ti_reports"
    nodeStageSecretRef:
      name: ti-collector-smb-secrets
      namespace: ti
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ti-collector-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  volumeName: ti-collector-pv
  storageClassName: ti-collector